project_name: "blackstone"
project_directory: "elt_gupy_scrapper"
dataset_id: blackstone-446301.elt_gupy_scrapper
local_file: "/tmp/all_jobs.json"

labels:
    - engenharia de software
    - analista de dados
    - cientista de dados
    - engenheiro de dados
    - desenvolvedor frontend
    - médico
    - enfermeiro
    - técnico de enfermagem
    - fisioterapeuta
    - farmacêutico
    - gerente de marketing
    - analista de marketing digital
    - coordenador de marketing
    - especialista em SEO
    - designer gráfico
    - engenheiro civil
    - engenheiro elétrico
    - engenheiro mecânico
    - engenheiro ambiental
    - engenheiro de produção
    - analista de recursos humanos
    - coordenador de RH
    - gerente de RH
    - especialista em recrutamento
    - consultor de RH


storage:
  { bucket_name: elt_gupy_scrapper,
    bucket_url: https://console.cloud.google.com/storage/browser/elt_gupy_scrapper,
    bucket_uri: gs://elt_gupy_scrapper
}

BigQuery: 
  stage:
    table_name: "blackstone-446301.elt_gupy_scrapper.gupy_jobs_stage"

  bronze:
    table_name: "blackstone-446301.elt_gupy_scrapper.gupy_jobs_bronze"
    query: |
      CREATE OR REPLACE TABLE `blackstone-446301.elt_gupy_scrapper.gupy_jobs_bronze` AS

      -- Mapeamento de Abreviação de Estados
      WITH state_mapping AS (
        SELECT 'acre' AS state_name, 'AC' AS state_abbreviation UNION ALL
        SELECT 'alagoas', 'AL' UNION ALL
        SELECT 'amapá', 'AP' UNION ALL
        SELECT 'amazonas', 'AM' UNION ALL
        SELECT 'bahia', 'BA' UNION ALL
        SELECT 'ceará', 'CE' UNION ALL
        SELECT 'distrito federal', 'DF' UNION ALL
        SELECT 'espírito santo', 'ES' UNION ALL
        SELECT 'goiás', 'GO' UNION ALL
        SELECT 'maranhão', 'MA' UNION ALL
        SELECT 'mato grosso', 'MT' UNION ALL
        SELECT 'mato grosso do sul', 'MS' UNION ALL
        SELECT 'minas gerais', 'MG' UNION ALL
        SELECT 'pará', 'PA' UNION ALL
        SELECT 'paraíba', 'PB' UNION ALL
        SELECT 'paraná', 'PR' UNION ALL
        SELECT 'pernambuco', 'PE' UNION ALL
        SELECT 'piauí', 'PI' UNION ALL
        SELECT 'rio de janeiro', 'RJ' UNION ALL
        SELECT 'rio grande do norte', 'RN' UNION ALL
        SELECT 'rio grande do sul', 'RS' UNION ALL
        SELECT 'rondônia', 'RO' UNION ALL
        SELECT 'roraima', 'RR' UNION ALL
        SELECT 'santa catarina', 'SC' UNION ALL
        SELECT 'são paulo', 'SP' UNION ALL
        SELECT 'sergipe', 'SE' UNION ALL
        SELECT 'tocantins', 'TO'
      ),
      
      -- Mapeamento de Categorias de Emprego
      job_category_mapping AS (
         -- TI & Desenvolvimento
        SELECT 'developer' AS keyword, 'TI & Desenvolvimento' AS job_category UNION ALL
        SELECT 'desenvolvedor', 'TI & Desenvolvimento' UNION ALL
        SELECT 'programador', 'TI & Desenvolvimento' UNION ALL
        SELECT 'engenheiro de software', 'TI & Desenvolvimento' UNION ALL
        SELECT 'software engineer', 'TI & Desenvolvimento' UNION ALL
        SELECT 'full stack', 'TI & Desenvolvimento' UNION ALL
        SELECT 'front-end', 'TI & Desenvolvimento' UNION ALL
        SELECT 'back-end', 'TI & Desenvolvimento' UNION ALL
        SELECT 'cloud', 'TI & Desenvolvimento' UNION ALL
        SELECT 'devops', 'TI & Desenvolvimento' UNION ALL

        -- Dados & Inteligência Artificial
        SELECT 'dados', 'Dados & IA' UNION ALL
        SELECT 'cientista de dados', 'Dados & IA' UNION ALL
        SELECT 'engenheiro de dados', 'Dados & IA' UNION ALL
        SELECT 'analista de dados', 'Dados & IA' UNION ALL
        SELECT 'machine learning', 'Dados & IA' UNION ALL
        SELECT 'big data', 'Dados & IA' UNION ALL
        SELECT 'inteligência artificial', 'Dados & IA' UNION ALL

        -- Administração & Financeiro
        SELECT 'administrador', 'Administração & Financeiro' UNION ALL
        SELECT 'contabilidade', 'Administração & Financeiro' UNION ALL
        SELECT 'financeiro', 'Administração & Financeiro' UNION ALL
        SELECT 'gestão', 'Administração & Financeiro' UNION ALL
        SELECT 'analista financeiro', 'Administração & Financeiro' UNION ALL
        SELECT 'controladoria', 'Administração & Financeiro' UNION ALL

        -- Vendas & Comercial
        SELECT 'vendas', 'Vendas & Comercial' UNION ALL
        SELECT 'comercial', 'Vendas & Comercial' UNION ALL
        SELECT 'representante de vendas', 'Vendas & Comercial' UNION ALL
        SELECT 'executivo de contas', 'Vendas & Comercial' UNION ALL
        SELECT 'customer success', 'Vendas & Comercial' UNION ALL
        SELECT 'key account', 'Vendas & Comercial' UNION ALL

        -- Atendimento & Suporte
        SELECT 'suporte', 'Atendimento & Suporte' UNION ALL
        SELECT 'atendimento', 'Atendimento & Suporte' UNION ALL
        SELECT 'help desk', 'Atendimento & Suporte' UNION ALL
        SELECT 'suporte técnico', 'Atendimento & Suporte' UNION ALL

        -- Marketing & Publicidade
        SELECT 'marketing', 'Marketing & Publicidade' UNION ALL
        SELECT 'mídias sociais', 'Marketing & Publicidade' UNION ALL
        SELECT 'growth', 'Marketing & Publicidade' UNION ALL
        SELECT 'publicidade', 'Marketing & Publicidade' UNION ALL
        SELECT 'SEO', 'Marketing & Publicidade' UNION ALL

        -- Recursos Humanos
        SELECT 'rh', 'Recursos Humanos' UNION ALL
        SELECT 'recrutamento', 'Recursos Humanos' UNION ALL
        SELECT 'talentos', 'Recursos Humanos' UNION ALL
        SELECT 'gestão de pessoas', 'Recursos Humanos' UNION ALL

        -- Engenharia & Manutenção
        SELECT 'engenheiro', 'Engenharia & Manutenção' UNION ALL
        SELECT 'técnico', 'Engenharia & Manutenção' UNION ALL
        SELECT 'manutenção', 'Engenharia & Manutenção' UNION ALL
        SELECT 'elétrica', 'Engenharia & Manutenção' UNION ALL
        SELECT 'mecânica', 'Engenharia & Manutenção' UNION ALL

        -- Saúde & Medicina
        SELECT 'enfermeiro', 'Saúde & Medicina' UNION ALL
        SELECT 'médico', 'Saúde & Medicina' UNION ALL
        SELECT 'fisioterapeuta', 'Saúde & Medicina' UNION ALL
        SELECT 'psicólogo', 'Saúde & Medicina' UNION ALL

        -- Educação
        SELECT 'professor', 'Educação' UNION ALL
        SELECT 'pedagogo', 'Educação' UNION ALL
        SELECT 'instrutor', 'Educação' UNION ALL
        SELECT 'educação', 'Educação'
      ),

      vacancy_type_mapping AS (
        -- Efetivo / CLT
        SELECT 'vacancy_type_effective' AS vacancy_key, 'Efetivo/CLT' AS vacancy_type UNION ALL
        SELECT 'vacancy_type_clt', 'Efetivo/CLT' UNION ALL

        -- Estágio
        SELECT 'vacancy_type_internship', 'Estágio' UNION ALL
        SELECT 'vacancy_type_stage', 'Estágio' UNION ALL

        -- Banco de Talentos
        SELECT 'vacancy_type_talent_pool', 'Banco de Talentos' UNION ALL

        -- Temporário
        SELECT 'vacancy_type_temporary', 'Temporário' UNION ALL
        SELECT 'vacancy_type_temp', 'Temporário' UNION ALL
        SELECT 'vacancy_type_contract', 'Temporário' UNION ALL

        -- Aprendiz
        SELECT 'vacancy_type_apprentice', 'Aprendiz' UNION ALL

        -- Freelancer / PJ
        SELECT 'vacancy_type_freelancer', 'Freelancer/PJ' UNION ALL
        SELECT 'vacancy_legal_entity', 'Freelancer/PJ' UNION ALL
        SELECT 'vacancy_type_consultant', 'Freelancer/PJ' UNION ALL

        -- Autônomo
        SELECT 'vacancy_type_autonomous', 'Autônomo' UNION ALL
        SELECT 'vacancy_type_cooperative', 'Autônomo' UNION ALL

        -- Professor
        SELECT 'vacancy_type_lecturer', 'Professor' UNION ALL

        -- Terceirização
        SELECT 'vacancy_type_outsource', 'Terceirização' UNION ALL

        -- Meio Período
        SELECT 'vacancy_type_part_time', 'Meio Período' UNION ALL

        -- Tempo Integral
        SELECT 'vacancy_type_full_time', 'Tempo Integral' UNION ALL

        -- Remoto
        SELECT 'vacancy_type_remote', 'Remoto' UNION ALL

        -- Voluntário
        SELECT 'vacancy_type_volunteer', 'Voluntário' UNION ALL

        -- Trainee
        SELECT 'vacancy_type_trainee', 'Trainee'
      )

      SELECT a.*,
          COALESCE(c.job_category, 'Outros') AS job_category,
          COALESCE(b.state_abbreviation, 'N/A') AS state_abbreviation,
          COALESCE(d.vacancy_type, 'Desconhecido') AS vacancy_type
      FROM `blackstone-446301.elt_gupy_scrapper.gupy_jobs_stage` AS a
      LEFT JOIN state_mapping AS b
        ON LOWER(a.state) = LOWER(b.state_name)
      LEFT JOIN job_category_mapping AS c
        ON LOWER(a.name) LIKE CONCAT('%', LOWER(c.keyword), '%')
      LEFT JOIN vacancy_type_mapping AS d
        ON LOWER(a.type) = LOWER(d.vacancy_key);

  silver:
    gupy_jobs_location:
      table_name: "blackstone-446301.elt_gupy_scrapper.gupy_jobs_location_silver"
      query: |
        CREATE OR REPLACE TABLE `blackstone-446301.elt_gupy_scrapper.gupy_jobs_location_silver` AS
        SELECT
        id AS job_id, 
        country,
        state,
        state_abbreviation,
        city

        FROM `blackstone-446301.elt_gupy_scrapper.gupy_jobs_bronze`;

    gupy_jobs_jobs:
      table_name: "blackstone-446301.elt_gupy_scrapper.gupy_jobs_jobs_silver"
      query: |
        CREATE OR REPLACE TABLE `blackstone-446301.elt_gupy_scrapper.gupy_jobs_jobs_silver` AS
        SELECT
        id AS job_id,
        job_category,
        vacancy_type,
        CASE 
            WHEN LOWER(workplaceType) = 'hybrid' THEN 'Híbrido'
            WHEN LOWER(workplaceType) = 'remote' THEN 'Remoto'
            WHEN LOWER(workplaceType) = 'on-site' THEN 'Presencial'
            ELSE 'Desconhecido' 
        END AS workplace_type,
        disabilities

        FROM `blackstone-446301.elt_gupy_scrapper.gupy_jobs_bronze`;
    
    gupy_jobs_company_and_time:
      table_name: "blackstone-446301.elt_gupy_scrapper.gupy_jobs_company_and_time_silver"
      query: |
        CREATE OR REPLACE TABLE `blackstone-446301.elt_gupy_scrapper.gupy_jobs_company_and_time_silver` AS
        SELECT
        id AS job_id,
        companyId AS company_id,
        careerPageName AS company_name,
        LOWER(name) AS job_title,
        FORMAT_DATE('%Y/%m/%d', DATE(publishedDate)) AS published_date,
        FORMAT_DATE('%Y/%m/%d', DATE(applicationDeadline)) AS application_dead_line,
        DATE_DIFF(IFNULL(DATE(applicationDeadline), CURRENT_DATE()), DATE(publishedDate), DAY) AS days_for_application
        
        FROM `blackstone-446301.elt_gupy_scrapper.gupy_jobs_bronze`;

    

  gold:
    table_name: "blackstone-446301.elt_gupy_scrapper.gupy_jobs_gold_for_analysis"
    query: |
      CREATE OR REPLACE TABLE `blackstone-446301.elt_gupy_scrapper.gupy_jobs_gold_for_analysis` AS
      SELECT
      a.*,
      b.* EXCEPT(job_id),
      c.* EXCEPT(city, job_id)

      FROM `blackstone-446301.elt_gupy_scrapper.gupy_jobs_jobs_silver` AS a
      LEFT JOIN `blackstone-446301.elt_gupy_scrapper.gupy_jobs_company_and_time_silver` AS b
        ON a.job_id = b.job_id
      LEFT JOIN `blackstone-446301.elt_gupy_scrapper.gupy_jobs_location_silver` AS c
        ON a.job_id = c.job_id;